// Generated by CoffeeScript 1.6.3
(function() {
  describe('deck', function() {
    var deck, hand;
    deck = null;
    hand = null;
    beforeEach(function() {
      deck = new Deck();
      return hand = deck.dealPlayer();
    });
    describe('hit', function() {
      return it("should give the last card from the deck", function() {
        expect(deck.length).toBe(50);
        expect(deck.last()).toEqual(hand.hit());
        expect(deck.length).toBe(49);
        expect(deck.last()).toEqual(hand.hit());
        return expect(deck.length).toBe(48);
      });
    });
    describe('stand', function() {
      it("should allow hit until stand", function() {
        hand.hit();
        return expect(deck.length).toBe(49);
      });
      return it("should not allow hit after stand", function() {
        hand.stand();
        hand.hit();
        return expect(deck.length).toBe(50);
      });
    });
    return describe('deal', function() {
      return it("should deal one dealer card face down", function() {
        var dealerHand;
        dealerHand = deck.dealDealer();
        return expect(dealerHand.at(0).get('revealed')).toBe(false);
      });
    });
  });

}).call(this);
