// Generated by CoffeeScript 1.6.3
(function() {
  describe("hands", function() {
    var dealer, deck, player;
    deck = null;
    player = null;
    dealer = null;
    beforeEach(function() {
      deck = new Deck();
      player = deck.dealPlayer();
      return dealer = deck.dealDealer();
    });
    describe('has we?', function() {
      it("we has.", function() {
        expect(player).toBeDefined();
        return expect(dealer.length).toEqual(2);
      });
      return it("the right number of cards", function() {
        expect(player.length).toEqual(2);
        player.hit();
        return expect(player.length).toEqual(3);
      });
    });
    return describe('they render', function() {
      return it('yes they do', function() {
        var handview;
        spyOn(HandView.prototype, 'render').andCallThrough();
        handview = new HandView({
          collection: player
        });
        console.log(HandView);
        return expect(HandView.prototype.render()).toHaveBeenCalled();
      });
    });
  });

}).call(this);
